### ISSUE TITLE
XSS vulnerability

### ISSUE THREAD

**Issue by injectnique** [Caerostris/Van2Shout#24]
Shoutbox is vulnerable to encoded XSS

Example:
ASCII:
<script>alert("XSS")</script>

Encoded:
%3C%73%63%72%69%70%74%3E%61%6C%65%72%74%28%22%58%53%53%22%29%3C%2F%73%63%72%69%70%74%3E

Looks like this has been an issue for some time
https://exchange.xforce.ibmcloud.com/#/vulnerabilities/83425

**Comment by Caerostris** [comment]
Thanks for reporting this!
I just had a look at the problem. The XSS vulnerability does not affect this version on github.
It does however affect the version currently public on vanillaforums.org.
The problematic line is not the escaping pointed out in 9a63f310f17a7c3737932d41c325307446d0b895.
The bug occurs due to an obsolete `unescape` in `views/discussionscontroller_local.php`.
I will upload a fix to vanillaforums.org in a second.

**Comment by Caerostris** [comment]
update published.

**Comment by ghost** [comment]
Thank you!
